---
l1Cat: "Coursework"
l2Cat: "Unit 1"
l3Cat: "Section 02 - Misc Operations"
title: "120 - try catch blocks"
layout: "../../../../layouts/Coursework.astro"
---

# Try catch blocks
Try catch blocks are usefull for allowing you to catch errors in your program before they cause programs to melt down. Keep in mind that they are not always neccecery, but can be very usefull when dealing with sections of code you know are hairy, or when you cannot ensure that user input is clean.

## Example 1
```python
def divide(x, y):
    z = x / y
    return(z)

try:
    num1 = int(input("Enter num 1: "))
    num2 = int(input("Enter num 2: "))
    print(divide(num1, num2))
except ValueError:
    print("You make a mistake, please enter a number!")
except:
    print("Error!")
```
